ARG IMG
FROM ${IMG}

RUN apk add \
  curl \
  jq \
  aws-cli \
  ansible \
  openssh-client

RUN curl -s -o packer_1.10.2_linux_amd64.zip https://releases.hashicorp.com/packer/1.10.2/packer_1.10.2_linux_amd64.zip && \
  unzip packer_1.10.2_linux_amd64.zip && \
  mv packer /usr/bin/packer && \
  chmod +x /usr/bin/packer

ENTRYPOINT [ "/usr/bin/packer" ]