ARG IMG
FROM ${IMG}
RUN apk add curl unzip git
RUN curl -sL https://releases.hashicorp.com/terraform/1.7.2/terraform_1.7.2_linux_amd64.zip -o terraform_1.7.2_linux_amd64.zip && \
  unzip terraform_1.7.2_linux_amd64.zip && rm -rf terraform_1.7.2_linux_amd64.zip && \
  mv terraform /usr/bin/
ENTRYPOINT [ "terraform" ]