FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get upgrade -y && apt-get install -y gcc default-jre curl unzip

WORKDIR /opt
RUN curl https://dlcdn.apache.org//jmeter/binaries/apache-jmeter-5.6.3.zip -o apache-jmeter-5.6.3.zip
RUN unzip apache-jmeter-5.6.3.zip

WORKDIR /opt/apache-jmeter-5.6.3/bin
CMD [ "./jmeter" ]
# CMD [ "./jmeter", "-n", "-t", "/app/testbase.jmx", "-l", "/opt/results.csv" ]